### ISSUE TITLE
Check in `Cargo.lock` for `pijul` binary

### ISSUE THREAD

**Issue by colemickens** [pijul/pijul#4]
Rust's recommendations are that libraries not check-in their `Cargo.lock`, but that the application binary should do so.

Additionally, I can't package `pijul 0.2` for NixOS without it (or without maintaining a fork that adds it).

**Comment by colemickens** [comment]
(Cross linking issues: https://github.com/NixOS/nixpkgs/issues/12924)

**Comment by pijul** [comment]
Done

**Comment by colemickens** [comment]
@pijul Where was it added at? I don't see it after doing a darcs clone or in the github mirror. What "revision" do I refer to?

**Comment by colemickens** [comment]
Hm, I do actually see it on github...

**Comment by colemickens** [comment]
Is GitHub now the authoritative repo? I'd prefer to point to the authoritative repo, whichever that may be. Thanks for adding it!

**Comment by FlorentBecker** [comment]
The authoritative repo is the darcs repo.

**Comment by colemickens** [comment]
Okay, it's just confusing because the `Cargo.lock` commit appears in the GitHub repo and not in the darcs repo...

**Comment by pijul** [comment]
Ooooh, I pushed it to our ssh, not to the public one. Let me change this now. Do you need a tag?

**Comment by colemickens** [comment]
It might be nice but it's not required.
